l_english:
 is_your_child_desc: "Çocuğunuz"
 is_your_close_family_desc: "Yakın Akrabanız"
 is_your_house_desc: "Hanenizden"
 landed_spouse_desc: "Eşi Toprak Sahibi"
 landed_heir_desc: "Vârisi Toprak Sahibi"
 has_many_good_relations_desc: "Çok Arkadaşı Var"
 has_many_bad_relations_desc: "Çok Rakibi var"
 part_of_feud_desc: "Kan Davası Var"
 high_diplomacy_desc: "Yüksek Diplomasi Sahibi"
 high_martial_desc: "Yüksek Askeriyeye Sahip"
 high_stewardship_desc: "Yüksek İdareye Sahip"
 high_intrigue_desc: "Yüksek Entrikaya Sahip"
 high_learning_desc: "Yüksek Öğrenime Sahip"
 high_prowess_desc: "Yüksek Dövüş Becerisine Sahip"
 high_education_desc: "İyi Bir Eğitime Sahip"
 more_beautiful_desc: "Vâristen daha Güzel"
 more_smart_desc: "Vâristen daha Zeki"
 more_fit_desc: "Vâristen daha Fit"
 more_strong_desc: "Vâristen daha Güçlü"
 more_skillful_desc: "Vâristen daha Becerikli"
 has_nickname_desc: "Lakabı Var"
 more_famous_desc: "Vâristen daha Ünlü"
 second_in_line_desc: "Verasette 2. Sırada"
 higher_title_desc: "Yüksek Unvan Sahibi"
 new_liege_desc: "Yeni Bir Süzeren Altında"
 new_top_liege_desc: "Yeni Bir Ana Süzeren Alındı"
 tall_claims_desc: "Önemli Hak İddiaları Var"
 pressed_claims_desc: "Güçlü Hak İddiaları Var"
 unpressed_claims_desc: "Zayıf Hak İddiaları Var"
 inheritance_line_desc: "Veraset Sırasında"
 has_interesting_story_desc: "İlginç Bir Hikâyesi Var"
 child_of_destiny_desc: "Kaderin Çocuğu"
 virtues_interesting_desc: "Erdemli Özelliklere Sahip"
 tourney_xp_desc: "Tecrübeli bir [GetTrait('tourney_participant').GetName( GetNullCharacter )]"
 reveler_xp_desc: "Tecrübeli bir [GetTrait('lifestyle_reveler').GetName( GetNullCharacter )]"
 mystic_xp_desc: "Experience as a [GetTrait('lifestyle_mystic').GetName( GetNullCharacter )]"
 hunter_xp_desc: "Tecrübeli bir [GetTrait('lifestyle_hunter').GetName( GetNullCharacter )]"
 blademaster_xp_desc: "Tecrübeli bir [GetTrait('lifestyle_blademaster').GetName( GetNullCharacter )]"
 traveler_xp_desc: "Tecrübeli bir [GetTrait('lifestyle_traveler').GetName( GetNullCharacter )]"
 physician_xp_desc: "Tecrübeli bir [GetTrait('lifestyle_physician').GetName( GetNullCharacter )]"
 herbalist_xp_desc: "Tecrübeli bir [GetTrait('lifestyle_herbalist').GetName( GetNullCharacter )]"
 loyal_interesting_desc: "O [GetTrait('loyal').GetName( GetNullCharacter )]"
 disloyal_interesting_desc: "O [GetTrait('disloyal').GetName( GetNullCharacter )]"
 faith_warrior_interesting_desc: "O [GetTrait('faith_warrior').GetName( GetNullCharacter )]"
 blood_of_prophet_interesting_desc: "[GetTrait('blood_of_prophet').GetName( GetNullCharacter )] Sahibi"
 poet_interesting_desc: "O bir [GetTrait('lifestyle_poet').GetName( GetNullCharacter )]"
 peasant_leader_interesting_desc: "O bir [GetTrait('peasant_leader').GetName( GetNullCharacter )]"
 populist_leader_interesting_desc: "O bir [GetTrait('populist_leader').GetName( GetNullCharacter )]"
 berserker_interesting_desc: "O bir [GetTrait('berserker').GetName( GetNullCharacter )]"
 born_in_the_purple_interesting_desc: "O [GetTrait('born_in_the_purple').GetName( GetNullCharacter )]"
 scaly_interesting_desc: "[GetTrait('scaly').GetName( GetNullCharacter )] Deri Sahibi"
 albino_interesting_desc: "O [GetTrait('albino').GetName( GetNullCharacter )]"
 dwarf_interesting_desc: "O bir [GetTrait('dwarf').GetName( GetNullCharacter )]"
 giant_interesting_desc: "O bir [GetTrait('giant').GetName( GetNullCharacter )]"
 devoted_interesting_desc: "O bir [GetTrait('devoted').GetName( GetNullCharacter )]"
 pure_blooded_interesting_desc: "O [GetTrait('pure_blooded').GetName( GetNullCharacter )]"
 crusader_king_interesting_desc: "O bir [GetTrait('crusader_king').GetName( GetNullCharacter )]"
 disinherited_interesting_desc: "O [GetTrait('disinherited').GetName( GetNullCharacter )]"
 blind_interesting_desc: "O [GetTrait('blind').GetName( GetNullCharacter )]"
 is_diarch_interesting_desc: "O bir Diark"
 ruler_in_foreign_lands_interesting_desc: "Yabancı Topraklarda Bir Hükümdar"
 valiant_knight_interesting_desc: "O Yiğit Bir Şövalye"
 sinful_bastard_interesting_desc: "O Günahkar Bir [GetTrait('bastard').GetName( GetNullCharacter )]"
 adventurer_interesting_desc: "O Maceracı"
 liege_crusader_king_liege_lineage_interesting_desc: "[GetTrait('crusader_king').GetName( GetNullCharacter )] Soyunun Süzereni"
 holy_site_steward_interesting_desc: "Başkenti Kutsal Bölge"
 has_a_legend_interesting_desc: "Destan Sahibi"
 weak_hook_liege_interesting_desc: "Süzeren Üzerinde Zayıf Koz Sahibi"
 strong_hook_liege_interesting_desc: "Süzeren Üzerinde Güçlü Koz Sahibi"
 beloved_by_pope_interesting_desc: "Papa Tarafından Seviliyor"
 head_of_faith_interesting_desc: "Mezhep Lideri"
 stronger_than_liege_interesting_desc: "Süzereninden Güçlü"
 small_king_interesting_desc: "Küçük Bir Krallığın Hükümdarı"
 can_feudalize_interesting_desc: "Feodalleşebilir"
 multiduke_interesting_desc: "Çok Fazla Düklüğe Sahip"
 legitimacy_interesting_desc: "Fazlasıyla Meşru Bir Hükümdar"
 non_dominant_gender_ambitious_char_interesting_desc: "Hırslı, Baskın Olmayan Cinsiyetten Karakter"
 non_dominant_gender_ruler_interesting_desc: "Baskın Olmayan Cinsiyetten Hükümdar"
 treacherous_schemer_interesting_desc: "Kurnaz bir Entrikacı"
 kind_hearted_diplomat_interesting_desc: "İyi Kalpli bir Diplomat"
 different_faith_interesting_desc: "Farklı Mezhepten"
 greedy_steward_interesting_desc: "O Açgözlü bir Vekilharç"
 brazen_commander_interesting_desc: "O Cesur bir Komutan"
 pious_theologian_interesting_desc: "O Dindar bir Teolog"
 salacious_seducer_interesting_desc: "O Cazibeli bir Baştan Çıkarıcı"
 high_skills_desc: "Yüksek Beceriler"
 killed_a_lot_interesting_desc: "10'dan Fazla Kişi Öldürdü"
 has_both_good_and_bad_genetics_desc: "Hem İyi Hem Kötü Genetik Özelliklere Sahip"
 good_genetics_desc: "İyi Genetik Özelliklere Sahip"
 bad_genetics_desc: "Kötü Genetik Özelliklere Sahip"
 holds_rome_interesting_desc: "[GetTitleByKey('c_roma').GetBaseName] Unvanını Elinde Tutuyor"
 holds_byzantion_interesting_desc: "[GetTitleByKey('c_byzantion').GetBaseName] Unvanını Elinde Tutuyor"
 holds_jerusalem_interesting_desc: "[GetTitleByKey('c_jerusalem').GetBaseName] Unvanını Elinde Tutuyor"
 holds_mecca_interesting_desc: "[GetTitleByKey('c_mecca').GetBaseName] Unvanını Elinde Tutuyor"
 holds_baghdad_interesting_desc: "[GetTitleByKey('c_baghdad').GetBaseName] Unvanını Elinde Tutuyor"
 holds_special_buildings_interesting_desc: "Özel Binaları Kontrol Ediyor"
 has_historical_artifacts_interesting_desc: "Tarihsel Eserlere Sahip"
 underrepresented_faith_interesting_desc: "Azınlık Mezhebine Mensup"
 underrepresented_culture_interesting_desc: "Azınlık Kültürüne Mensup"
 outside_realm_desc: "Bağımsız Hükümdar"
 knows_many_secrets_interesting_desc: "Çok Sır Biliyor"
 has_secrets_interesting_desc: "Sırları Var"
 extremely_wealthy_interesting_desc: "Çok Zengin"
 landless_heir_uninteresting_desc: "Topraksız Unvan Vârisi"
 three_virtues_desc: "Üç Erdemli Özelliğe Sahip"
 three_sins_desc: "Üç Günahkar Özelliğe Sahip"
 skills_difficulty: "Becerilerden"
 legitimacy_difficulty: "Meşruiyetten"
 virtuous_traits_difficulty: "Erdemli Özelliklere Sahip"
 physique_good_3_difficulty: "O [GetTrait('physique_good_3').GetName( GetNullCharacter )]"
 physique_good_2_difficulty: "O [GetTrait('physique_good_2').GetName( GetNullCharacter )]"
 physique_good_1_difficulty: "O [GetTrait('physique_good_1').GetName( GetNullCharacter )]"
 intellect_good_3_difficulty: "O [GetTrait('intellect_good_3').GetName( GetNullCharacter )]"
 intellect_good_2_difficulty: "O [GetTrait('intellect_good_2').GetName( GetNullCharacter )]"
 intellect_good_1_difficulty: "O [GetTrait('intellect_good_1').GetName( GetNullCharacter )]"
 beauty_good_3_difficulty: "O [GetTrait('beauty_good_3').GetName( GetNullCharacter )]"
 beauty_good_2_difficulty: "O [GetTrait('beauty_good_2').GetName( GetNullCharacter )]"
 beauty_good_1_difficulty: "O [GetTrait('beauty_good_1').GetName( GetNullCharacter )]"
 shrewd_difficulty: "O [GetTrait('shrewd').GetName( GetNullCharacter )]"
 strong_difficulty: "O [GetTrait('strong').GetName( GetNullCharacter )]"
 sinful_traits_difficulty: "Günahkar Özelliklere Sahip"
 incapable_difficulty: "O [GetTrait('incapable').GetName( GetNullCharacter )]"
 leper_difficulty: "O bir [GetTrait('leper').GetName( GetNullCharacter )]"
 maimed_difficulty: "O [GetTrait('maimed').GetName( GetNullCharacter )]"
 inbred_difficulty: "O [GetTrait('inbred').GetName( GetNullCharacter )]"
 severely_wounded_difficulty: "Yaralı"
 disinherited_difficulty: "O [GetTrait('disinherited').GetName( GetNullCharacter )]"
 sickly_difficulty: "O [GetTrait('sickly').GetName( GetNullCharacter )]"
 poxed_difficulty: "Has the [GetTrait('great_pox').GetName( GetNullCharacter )]"
 blind_difficulty: "O [GetTrait('blind').GetName( GetNullCharacter )]"
 infirm_difficulty: "O [GetTrait('infirm').GetName( GetNullCharacter )]"
 eunuch_difficulty: "O bir [GetTrait('eunuch_1').GetName( GetNullCharacter )]"
 lunatic_difficulty: "O bir [GetTrait('lunatic').GetName( GetNullCharacter )]"
 murderer_difficulty: "O bir [GetTrait('murderer').GetName( GetNullCharacter )]"
 excommunicated_difficulty: "Aforoz Edilmiş"
 bleeder_difficulty: "O bir [GetTrait('bleeder').GetName( GetNullCharacter )]"
 physique_bad_3_difficulty: "O [GetTrait('physique_bad_3').GetName( GetNullCharacter )]"
 physique_bad_2_difficulty: "O [GetTrait('physique_bad_2').GetName( GetNullCharacter )]"
 physique_bad_1_difficulty: "O [GetTrait('physique_bad_1').GetName( GetNullCharacter )]"
 intellect_bad_3_difficulty: "O [GetTrait('intellect_bad_3').GetName( GetNullCharacter )]"
 intellect_bad_2_difficulty: "O [GetTrait('intellect_bad_2').GetName( GetNullCharacter )]"
 intellect_bad_1_difficulty: "O [GetTrait('intellect_bad_1').GetName( GetNullCharacter )]"
 beauty_bad_3_difficulty: "O [GetTrait('beauty_bad_3').GetName( GetNullCharacter )]"
 beauty_bad_2_difficulty: "O [GetTrait('beauty_bad_2').GetName( GetNullCharacter )]"
 beauty_bad_1_difficulty: "O [GetTrait('beauty_bad_1').GetName( GetNullCharacter )]"
 dull_difficulty: "O [GetTrait('dull').GetName( GetNullCharacter )]"
 weak_difficulty: "O [GetTrait('weak').GetName( GetNullCharacter )]"
 sodomite_difficulty: "O bir [GetTrait('sodomite').GetName( GetNullCharacter )]"
 incestuous_difficulty: "O [GetTrait('incestuous').GetName( GetNullCharacter )]"
 fornicator_difficulty: "O bir [GetTrait('fornicator').GetName( GetNullCharacter )]"
 adulterer_difficulty: "O bir [GetTrait('adulterer').GetName( GetNullCharacter )]"
 cannibal_difficulty: "O bir [GetTrait('cannibal').GetName( GetNullCharacter )]"
 witch_difficulty: "O bir [GetTrait('witch').GetName( GetNullCharacter )]"
 kinslayer_difficulty: "O bir [GetTrait('kinslayer_1').GetName( GetNullCharacter )]"
 flagellant_difficulty: "O bir [GetTrait('flagellant').GetName( GetNullCharacter )]"
 improvident_difficulty: "O [GetTrait('improvident').GetName( GetNullCharacter )]"
 profligate_difficulty: "O [GetTrait('profligate').GetName( GetNullCharacter )]"
 disfigured_difficulty: "O [GetTrait('disfigured').GetName( GetNullCharacter )]"
 drunkard_difficulty: "O bir [GetTrait('drunkard').GetName( GetNullCharacter )]"
 possessed_difficulty: "O [GetTrait('possessed').GetName( GetNullCharacter )]"
 depressed_difficulty: "O [GetTrait('depressed').GetName( GetNullCharacter )]"
 infertile_difficulty: "O [GetTrait('infertile').GetName( GetNullCharacter )]"
 spindly_difficulty: "O [GetTrait('spindly').GetName( GetNullCharacter )]"
 paranoid_difficulty: "O [GetTrait('paranoid').GetName( GetNullCharacter )]"
 gout_difficulty: "O [GetTrait('gout_ridden').GetName( GetNullCharacter )]"
 wheezing_difficulty: "O [GetTrait('wheezing').GetName( GetNullCharacter )]"
 craven_difficulty: "O [GetTrait('craven').GetName( GetNullCharacter )]"
 shy_difficulty: "O [GetTrait('shy').GetName( GetNullCharacter )]"
 decadent_difficulty: "O [GetTrait('decadent').GetName( GetNullCharacter )]"
 denounced_difficulty: "O [GetTrait('denounced').GetName( GetNullCharacter )]"
 bastard_difficulty: "O bir [GetTrait('bastard').GetName( GetNullCharacter )]"
 weak_heritage_difficulty: "Zayıf Mirasa Sahip"
 comfort_eater_difficulty: "O bir [GetTrait('comfort_eater').GetName( GetNullCharacter )]"
 inappetetic_difficulty: "O [GetTrait('inappetetic').GetName( GetNullCharacter )]"
 reclusive_difficulty: "O [GetTrait('reclusive').GetName( GetNullCharacter )]"
 irritable_difficulty: "O [GetTrait('irritable').GetName( GetNullCharacter )]"
 rakish_difficulty: "O [GetTrait('rakish').GetName( GetNullCharacter )]"
 hashishiyah_difficulty: "O bir [GetTrait('hashishiyah').GetName( GetNullCharacter )]"
 celibate_difficulty: "O [GetTrait('celibate').GetName( GetNullCharacter )]"
 lovers_pox_difficulty: "O [GetTrait('lovers_pox').GetName( GetNullCharacter )] Sahibi"
 wounded_difficulty: "O [GetTrait('wounded_1').GetName( GetNullCharacter )]"
 albino_difficulty: "O [GetTrait('albino').GetName( GetNullCharacter )]"
 lisping_difficulty: "O [GetTrait('lisping').GetName( GetNullCharacter )]"
 stuttering_difficulty: "O bir [GetTrait('stuttering').GetName( GetNullCharacter )]"
 giant_difficulty: "O bir [GetTrait('giant').GetName( GetNullCharacter )]"
 scaly_difficulty: "O [GetTrait('scaly').GetName( GetNullCharacter )] Derili"
 clubfooted_difficulty: "O [GetTrait('clubfooted').GetName( GetNullCharacter )]"
 dwarf_difficulty: "O bir [GetTrait('dwarf').GetName( GetNullCharacter )]"
 hunchbacked_difficulty: "O [GetTrait('hunchbacked').GetName( GetNullCharacter )]"
 lazy_difficulty: "O [GetTrait('lazy').GetName( GetNullCharacter )]"
 gluttonous_difficulty: "O [GetTrait('gluttonous').GetName( GetNullCharacter )]"
 deviant_difficulty: "O bir [GetTrait('deviant').GetName( GetNullCharacter )]"
 at_war_difficulty: "Savaşta"
 losing_war_difficulty: "Savaş Kaybediyor"
 faction_difficulty: "Güçlü Örgütleşmelerin Hedefinde"
 powerful_neighbors_difficulty: "Güçlü Komşu Hükümdarlar"
 military_difficulty: "Askerî Güç"
 rivals_difficulty: "Rakipleri Var"
 primary_heir_wrong_dynasty_difficulty: "Vârisi Başka Hanedana Mensup"
 children_wrong_dynasty_difficulty: "Çocukları Başka Hanedana Mensup"
 hostile_faith_liege_difficulty: "Süzeren Düşmancıl bir Mezhepten"
 nonpreferred_gender_difficulty: "Mezhepte Tercih Edilmeyen bir Cinsiyetten"
 wrong_lineality_difficulty: "Yanlış Soylu bir Evlilikte"
 stress_level_difficulty: "Yüksek Stres Seviyesi"
 gold_difficulty: "Aşırı Zenginlik"
 debt_level_difficulty: "Yüksek Borçlanma"
 is_ill_difficulty: "Yatalak Bırakan bir Hastalıktan Muzdarip"
 imprisoned_difficulty: "Hapsedilmiş"
 elder_difficulty: "İleri Yaş"
 poor_health_difficulty: "Zayıf Sağlık"
 is_a_vassal_difficulty: "O bir Vassal"
 non_adult_difficulty: "Çocuk"
 weak_domain_difficulty: "Zayıf Mülk"
 unlanded_difficulty: "Unvansız"
 character_difficulty_text: "Zorluk: [Character.Custom('CharacterDifficulty')]"
 character_difficulty_breakdown_header: "Zorluk Özeti"
 choose_destiny_header_text: "Yeni bir Kader Seç"
 will_become_adventurer: "[GetGovernment('landless_adventurer_government').GetName] olacaksınız"
 character_interest_breakdown_header: "İlginç Yönler"
 different_government_desc: "Farklı bir Yönetim Biçimine Sahip"
 opposite_struggle_faction_desc: "Mücadelede Karşı Tarafta"
