l_english:

 impart_values.0001.t:0 "Ömür Boyu Bir Ders Vermek"

 impart_values.0001.desc:0 "#italic Ah, genç olmak, dolu dolu ve dinç olmak. Önünde keşfedilmeyi bekleyen koca bir dünya. Ve kişiliğin, kendin için bile bir muamma.#!\n\nİçeriye [recipient.Custom('InsultAdjective')] [ROOT.Char.Custom2('RelationToMeShort', recipient)] [recipient.GetTitledFirstName], her zamanki dikkatsizliğiyle girdiğinde kendimi gençliğin kararsızlığı üzerine düşünürken buluyorum.\n\n[recipient.GetHerHim]'i görmek içimde bir şeyler uyandırıyor: #bold Bu çocuğa hayatta neyin önemli olduğuna dair bir ders vereceğim.#!"

 already_imparted_lesson_desc:0 "[CHARACTER.GetShortUINameNoTooltip]'e hayatta nelere değer vereceğini öğretmeye zaten kalkıştın."

 impart_values.0001.diligent:0 "[recipient.GetSheHe] sebatkâr çalışmanın her zaman işine yarayacağını öğrenecek."

 impart_values.0001.lazy:0 " [recipient.GetFirstName], işleri başkalarının halletmesine izin vermeyi öğrenmeli."

 impart_values.0001.cynical:0 "[recipient.GetSheHe] başkalarının niyetlerini her zaman sorgulamayı öğrenmeli."

 impart_values.0001.zealous:0 "[recipient.GetHerHim]'e inancın büyük önem taşıdığını öğreteceğim."

 impart_values.0001.brave:0 "[recipient.GetFirstName], hiçbir hasma karşı korkusuz olmayı öğrenecek."

 impart_values.0001.craven:0 "Tüm korkulardan sakınmak, dikkate alınacak akıllıca bir derstir."

 impart_values.0001.calm:0 "[recipient.GetFirstName]'e sakin kalmanın önemini aşılayacağım."

 impart_values.0001.wrathful:0 "[recipient.GetHerHim]'e öğreteceğim şey, öfke ve hiddetle hareket etmektir."

 impart_values.0001.chaste:0 "[recipient.GetFirstName] doğal arzuların her türlü cazibesinden uzak durmalı."

 impart_values.0001.lustful:0 "[recipient.GetFirstName] doğal arzularını kucaklamayı öğrenmeli."

 impart_values.0001.content:0 "[recipient.GetHerHim]'e halihazırda sahip olduklarıyla yetinmeyi öğreteceğim."

 impart_values.0001.ambitious:0 "[recipient.GetHerHim]'e hırsın önemini öğreteceğim."

 impart_values.0001.fickle:0 "[recipient.GetHerHim]'e fikir değiştirmenin arzu edilir bir özellik olduğunu öğreteceğim."

 impart_values.0001.stubborn:0 "[recipient.GetSheHe]'ye hiçbir muhalefet karşısında geri adım atmaması öğretilecek."

 impart_values.0001.forgiving:0 "[recipient.GetSheHe] başkalarına merhamet göstermenin önemini öğrenecek."

 impart_values.0001.vengeful:0 "[recipient.GetHerHim]'e kendilerine haksızlık eden insanları asla unutmamayı öğreteceğim."

 impart_values.0001.generous:0 "[recipient.GetHerHim]'e hayır işlerinin sonsuz anlam taşıdığını göstereceğim."

 impart_values.0001.greedy:0 "Keseyi sıkı tutmak her zaman öğrenilecek iyi bir derstir."

 impart_values.0001.gregarious:0 "[recipient.GetHerHim]'e başkalarının meclisinin zevklerini göstereceğim."

 impart_values.0001.shy:0 "[recipient.GetHerHim]'e yalnız olmanın huzurlu faydalarını öğreteceğim."

 impart_values.0001.honest:0 "[recipient.GetSheHe] doğruluğun ve samimiyetin temel değerler olduğunu öğrenecek."

 impart_values.0001.deceitful:0 "[recipient.GetFirstName]'e nefes almak kadar kolay yalan söylemeyi öğreteceğim."

 impart_values.0001.humble:0 "Mütevazı bir yaşam, [recipient.GetFirstName]'in öğrenebileceği sade bir zevktir."

 impart_values.0001.arrogant:0 "[recipient.GetSheHe] öz değer duygusunun her şeyin üstünde olduğunu öğrenecek."

 impart_values.0001.just:0 "[recipient.GetHerHim]'e tanrıların ve insanların yasalarına uymayı öğreteceğim."

 impart_values.0001.arbitrary:0 "Başkalarını umursamadan kendi bildiklerini okumayı öğrenmeli."

 impart_values.0001.patient:0 "[recipient.GetHerHim]'e aşılayacağım şey, sabrın önemidir."

 impart_values.0001.impatient:0 "[recipient.GetHerHim]'e sonuçların gecikmesi karşısında sabırsızlanmayı öğreteceğim."

 impart_values.0001.temperate:0 "[recipient.GetSheHe] her şeyin ölçülü alınması gerektiğini öğrenecek."

 impart_values.0001.gluttonous:0 "[recipient.GetFirstName], zevkli şeylerin bolluğuna gark olmalı."

 impart_values.0001.trusting:0 "[recipient.GetSheHe] çevresindekilere güvenmeyi öğrenecek."

 impart_values.0001.paranoid:0 "[recipient.GetFirstName] her an arkasını kollamayı öğrenmeli."

 impart_values.0001.compassionate:0 "[recipient.GetFirstName]'e her şeyden önce şefkat öğretilecek."

 impart_values.0001.callous:0 "Başkalarının sorunlarını görmezden gelmek [recipient.GetFirstName]'in işine yarayacak."

 impart_values.0001.sadistic:0 "[recipient.GetHerHim]'e başkalarına zarar vermenin hazzını öğreteceğim."

 impart_values.0001.rude:0 "[recipient.GetHerHim]'e ne kadar pervasızca olursa olsun aklından geçeni söylemeyi öğreteceğim."

 impart_values.0001.honorable:0 "[recipient.GetFirstName]'e ahlakını yüksek tutmayı öğreteceğim."

 impart_values.0001.ruthless:0 "[recipient.GetSheHe] hedeflerine ulaşmak için acımasız olmayı öğrenecek."

 impart_values.0001.authoritative:0 "[recipient.GetHerHim]'e otoriter olmanın önemini öğreteceğim."

 impart_values.0001.inquisitive:0 "[recipient.GetSheHe] bilgi peşinde koşmanın değerini öğrenecek."

 impart_values.0001.backout:0 "Boş ver, [recipient.GetSheHe]'nin hazır olduğunu sanmıyorum."

 impart_values_lesson_ignored_title:0 "Ders Göz Ardı Edildi"

 impart_values_lesson_ignored_desc:0 "[recipient.GetShortUINameNoTooltip], derslerine hiç ilgi göstermedi."

 impart_values_lesson_success_title:0 "Ders Başarılı"

 impart_values_lesson_success_desc:0 "[recipient.GetShortUINameNoTooltip] derslerini özümsedi ve [recipient.Custom('TraitLearned')] özelliğini kazandı."

 impart_values_lesson_failure_title:0 "Ders Başarısız"

 impart_values_lesson_failure_desc:0 "[recipient.GetShortUINameNoTooltip] derslerine isyan etti ve [recipient.Custom('TraitLearned')] özelliğini kazandı."
