l_english:

 at_artifact_price_qwa_desc:0 "Kalite ve Servet"

 at_artifact_price_durability_desc:0 "Dayanıklılık"

 at_artifact_price_destroy_desc:0 "Sıradan veya Ustalık Eseri"

 at_artifact_price_unique_desc:0 "Eşsiz"

 at_artifact_ask_price_player_desc:0 "Kâr Marjı"

 at_artifact_ask_price_ai_greed_desc:0 "Satıcının Hırsı"

 at_artifact_bid_price_ai_greed_desc:0 "Alıcının Hırsı"
