l_english:
### TODO NOT-IN-ST: at_artifact_price_qwa_desc [AGOT: Quality & Wealth]
 at_artifact_price_qwa_desc: "Quality & Wealth"
### TODO NOT-IN-ST: at_artifact_price_durability_desc [AGOT: Durability]
 at_artifact_price_durability_desc: "Durability"
### TODO NOT-IN-ST: at_artifact_price_destroy_desc [AGOT: Common or Masterwork]
 at_artifact_price_destroy_desc: "Common or Masterwork"
### TODO NOT-IN-ST: at_artifact_price_unique_desc [AGOT: Unique]
 at_artifact_price_unique_desc: "Unique"
### TODO NOT-IN-ST: at_artifact_ask_price_player_desc [AGOT: Profit Margin]
 at_artifact_ask_price_player_desc: "Profit Margin"
### TODO NOT-IN-ST: at_artifact_ask_price_ai_greed_desc [AGOT: Seller Greed]
 at_artifact_ask_price_ai_greed_desc: "Seller Greed"
### TODO NOT-IN-ST: at_artifact_bid_price_ai_greed_desc [AGOT: Buyer Greed]
 at_artifact_bid_price_ai_greed_desc: "Buyer Greed"
